In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('train.txt',sep = ';',header = None,names = ['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [6]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [10]:
cols = df["emotion"].unique()

print(cols)

['sadness' 'anger' 'love' 'surprise' 'fear' 'joy']

# Converting to lower

In [13]:
from sklearn.preprocessing import LabelEncoder

labels = ['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']

le = LabelEncoder()

encoded = le.fit_transform(labels)

print(encoded)
print(le.classes_)

[4 0 3 5 1 2]
['anger' 'fear' 'joy' 'love' 'sadness' 'surprise']

In [15]:
df["text"] = df["text"].str.lower()

In [18]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

# Removing Punctuations

In [27]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

df["text"]  = df["text"].apply(remove_punc)

# Removing Numbers

In [28]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [25]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)