In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.txt',sep = ';',header = None,names = ['text','emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
cols = df["emotion"].unique()

print(cols)

['sadness' 'anger' 'love' 'surprise' 'fear' 'joy']

# Converting to lower

In [6]:
from sklearn.preprocessing import LabelEncoder

labels = ['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']

le = LabelEncoder()

df["emotion"] = le.fit_transform(df["emotion"])

print(le.classes_)

['anger' 'fear' 'joy' 'love' 'sadness' 'surprise']

In [7]:
df["text"] = df["text"].str.lower()

In [8]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

# Removing Punctuations

In [9]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

df["text"]  = df["text"].apply(remove_punc)

# Removing Numbers

In [10]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

# Removing Emojis

In [11]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

# Removing URLs and html tags are not included here

# __________________________________________________________________________________________

# Removing stopwords

In [12]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [13]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /home/muntaha/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/muntaha/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/muntaha/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
stop_words = set(stopwords.words('english'))

In [15]:
df['text'][1]

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [16]:
def remove(txt):
  words = word_tokenize(txt)
  cleaned = []  
  for i in words:
      if i not in stop_words:
          cleaned.append(i)
  return ' '.join(cleaned)  

df['text'] = df['text'].apply(remove)

In [17]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'